### PR TITLE
fix(carousel): arrow keys break animation if carousel sliding

### LINKED ISSUE #34290: v5 - carousel animation breaks
Hey,

there is a bug with the carousel component when you rapidly change slides in different directions.

Steps to reproduce:
- Go to [carousel docs](https://getbootstrap.com/docs/5.0/components/carousel/#with-controls)
- Focus the carousel example with controls, i.e. left and right arrow key should change slides
- Press left arrow key. Now press the right arrow key during the slide change animation
- Now the carousel is broken

This also occurs on mobile when you try to pinch-zoom an image in a carousel and the gesture is detected as left and right movement separately

Best regards,
Stefan

### PR DESCRIPTION
**Pull request by alpadev**
fixes #34290

~Alternatively I guess we could remove those if conditions and add one to the `_slide` method but that would require changes to the tests as well.~

### CODE REVIEW

File: js/src/carousel.js [hunk 1]
```diff
@@ -240,7 +245,9 @@ class Carousel extends BaseComponent {
       return
     }
 
-    this._slide(direction > 0 ? DIRECTION_RIGHT : DIRECTION_LEFT)
+    if (!this._isSliding) {
```
Comment (GeoSot) [inline js/src/carousel.js:248]: Better to do one check for all in start of `isSliding` method 😉

Comment (alpadev) [reply js/src/carousel.js]: That's what I said..

**Review by GeoSot — APPROVED** [review]
