### PR TITLE
Fix carousel buttons

### LINKED ISSUE #34226: Carousel controls broken in `main`
currently the carousel **prev and next buttons not working**, the indicators are working.

can anyone confirm this problem?

https://jsfiddle.net/jonnysp/dfz3x7at/

### PR DESCRIPTION
**Pull request by alpadev**
Fixes #34226

/cc @GeoSot

### CODE REVIEW

**Review by mdo — APPROVED** [review]
😻

File: js/src/carousel.js [hunk 1]
```diff
@@ -498,7 +498,14 @@ class Carousel extends BaseComponent {
...
 
-    const { _config } = data
+    let { _config } = data
+    if (typeof config === 'object') {
+      _config = {
+        ..._config,
+        ...config
+      }
+    }
+
```
Comment (GeoSot) [inline js/src/carousel.js:508]: @alpa Glad you find it :heart: 

Can you explain why did this happened? 

As it passes from `getOrCreateInstance`

```js

 static getOrCreateInstance(element, config = {}) {
    return this.getInstance(element) || new this(element, typeof config === 'object' ? config : null)
  } 
```


I am not sure I understand where it fails :/ 

and  `_getConfig` does the same process 

```js


  _getConfig(config) {
    config = {
      ...Default,
      ...Manipulator.getDataAttributes(this._element),
      ...(typeof config === 'object' ? config : {})
    }
    typeCheckConfig(NAME, config, DefaultType)
    return config
  }

```
