### PR TITLE
Fix bug multiple accordions collapse

### LINKED ISSUE #18824: multiple accordions collapse bug
Added two accordions both with all unique IDs. Page load fine. Each with one panel open. Now clicking a panel on one accordion to open leads to other accordion's panel to close. See example here: https://jsfiddle.net/leymannx/9x92umfk/

### PR DESCRIPTION
**Pull request by Johann-S**
Fix #18824

~~I'll add a unit test~~

Closes : #18824

### CODE REVIEW

File: js/tests/unit/collapse.js [hunk 1]
```diff
@@ -52,6 +52,16 @@ $(function () {
     assert.ok(!/height/i.test($el.attr('style')), 'has height reset')
   })
 
+  QUnit.test('should collapse only the first collapse', function (assert) {
```
Comment (cvrebert) [inline js/tests/unit/collapse.js]: The collapse that you toggle needs to be within an accordion, so that it has a parent and thus triggers the code path that you've changed.

Comment (Johann-S) [inline js/tests/unit/collapse.js]: Yes you're right thank you !

**Comment by Johann-S** [comment]
Any feedbacks @cvrebert ?

**Comment by DrChills** [comment]
+1

**Comment by stafast** [comment]
`$.makeArray($(this._parent).find(Selector.ACTIVES))`
Working fine for me, thanks.

**Comment by Johann-S** [comment]
you're welcome @stafast :+1:

**Comment by yellow1912** [comment]
Will this be merged soon? I would like to get this bug fix asap. Hopefully it will also fix my issue with nested collapse where clicking the child also closes the parent.

**Comment by Johann-S** [comment]
I hope this PR will be merged soon, but no review since January...

**Comment by mdo** [comment]
@Johann-S This is a bit out of date with the new card classes. Any chance you can update it? :D

**Comment by Johann-S** [comment]
Sure I'll work on it :)

**Comment by Johann-S** [comment]
I think all it's done @mdo 💪

**Comment by mdo** [comment]
Thanks so much! I'll get this into the next alpha as soon as I can :).
