### PR TITLE
Fix modal event-listeners during dismiss click

### LINKED ISSUE #36855: Scrollbar click closes modal with long content
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Previously on v5.1 when a modal was open, I was able to scroll throw the content by clicking any part of the window scrollbar, now on 5.2 clicking the scrollbar closes automatically the modal.

I tested on bootstrap docs page just to be sure I wasn't doing anything different and the issue can be tested by opening the demo modal for long content and clicking the scrollbar.

### Reduced test cases

v5.1 (scroll bar click works)
https://getbootstrap.com/docs/5.1/components/modal/#scrolling-long-content

v5.2.0 (scroll bar click closes modal)
https://getbootstrap.com/docs/5.2/components/modal/#scrolling-long-content

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.2.0

### PR DESCRIPTION
**Pull request by GeoSot**
Partially regression of #36401.

Fixes modal listeners in order to:
* ignore clicks on scrollbar
    * `mousedown`, `mouseup` listen to scrollbar click
    * `click` ignores scrollbar click
* ignores clicks that starts inside `.modal-dialog`, but ends outside of it
* react on clicks that start & end outside `.modal-dialog`

closes: #36855

alternative approach https://github.com/twbs/bootstrap/issues/36855#issuecomment-1206174935

### CODE REVIEW

File: js/src/modal.js [hunk 1]
```diff
@@ -30,7 +30,8 @@ const EVENT_HIDDEN = `hidden${EVENT_KEY}`
 const EVENT_SHOW = `show${EVENT_KEY}`
 const EVENT_SHOWN = `shown${EVENT_KEY}`
 const EVENT_RESIZE = `resize${EVENT_KEY}`
-const EVENT_MOUSEDOWN_DISMISS = `mousedown.dismiss${EVENT_KEY}`
+const EVENT_CLICK_DISMISS = `click.dismiss${EVENT_KEY}`
+const EVENT_MOUSDOWN_DISMISS = `mousedown.dismiss${EVENT_KEY}`
```
Comment (folknor) [inline js/src/modal.js:34]: Missing 'E' in variable name.

**Comment by mdo** [comment]
Is this good to merge @GeoSot or do you need a review from someone?

**Comment by GeoSot** [comment]
I would appreciate a review just to be sure

**Review by julien-deramond — APPROVED** [review]
I prefer this one compared to the alternative approach.

Tested the whole Modals page on macOS with different browsers (Firefox, Chrome, Edge and Safari) and couldn't spot any regressions.

LGTM! 🚀

**Comment by neoteknic** [comment]
@GeoSot Any 5.2.2 release ? Can you disable 5.2.1 because it broke many projets. Have to force 5.2.0 for now.

**Comment by folknor** [comment]
> @GeoSot Any 5.2.2 release ? Can you disable 5.2.1 because it broke many projets. Have to force 5.2.0 for now.

Yes, please do a 5.2.2 soon. Thank you!

**Comment by GeoSot** [comment]
I can understand you on this. I personally, have done a lot of refactoring to bring our codebase to a better condition, preparing it for v6, and unfortunately sometimes mistakes can be done. I apologize for this.
Furthermore, as a team, we are trying our best, working on our free time, so please make some patience and we will try to have a release soon

**Comment by XhmikosR** [comment]
I will release 5.2.2 tomorrow or Monday. Please be patient.
