### PR TITLE
Fix #17964

### LINKED ISSUE #17964: v4 Modal transition (fade) violates CSP (script-src 'unsafe-inline')
Modals with the .fade class trigger an error on show, causing the modal to fail to show and scripts to stop working requiring a page reload. This wasn't a problem in v3 and seems to be caused by the reflow function trying to eval() and inject javascript in the page.

Using branch v4-dev in a Meteor app.

### PR DESCRIPTION
**Pull request by deilv**
Some browsers are lazy when updating dom elements after transition effects. This can be fixed by reading element properties such as offsetHeight or offsetWidth, which causes the browser to resync (reflow) the element.

However, creating a function using the Function constructor just to access such element properties, results in a violation of Content Security Policy (where applied), which in turn crashes the application. This fix actually reverts to the way this was handled in v3 and should work as intended.

### CODE REVIEW

File: js/src/util.js [hunk 1]
```diff
@@ -116,7 +116,7 @@ const Util = (($) => {
     },
 
     reflow(element) {
-      new Function('bs', 'return bs')(element.offsetHeight)
+      return element.offsetHeight
```
Comment (vsn4ik) [inline js/src/util.js]: Semicolon is forbidden.

Comment (vsn4ik) [inline js/src/util.js]: It is necessary to adjust the hound...

Comment (vsn4ik) [inline js/src/util.js]: `javascript` write without `_` (undescore) https://houndci.com/configuration#javascript.

I think `java_script` is ignore in `.hound.yml`

Comment (cvrebert) [inline js/src/util.js]: Thanks, fixed in 18ad53fc5662e0739a32f86d8dcbfbf5bd5b260a

**Comment by mdo** [comment]
Curious if I could get some eyes on this from other folks who've pushed JS changes—@cvrebert, @Johann-S, or @bardiharborow. Know it's a small change, but I don't know the full context here <3.

**Comment by bardiharborow** [comment]
I actually did see this in the code and was wondering what we should do about it. The concern I have is that it was probably written in such a novel way because of a browser bug and I would want to ensure that it isn't still necessarily. So far I've traced it back to 834220e, but there is little indication why it was added.

**Comment by mdo** [comment]
I'll punt it to Alpha 6 until we know more then. We can always ping @fat to see if it needs to stay the same, but if this is coming from that Closure commit, I'm willing to bet it's not a weird browser thing. Thanks for looking!

**Comment by bardiharborow** [comment]
I've found [some](http://stackoverflow.com/a/3485654/1414639) [references](http://stackoverflow.com/q/8840580/1414639) to this technique on StackExchange

**Comment by mdo** [comment]
Okay, so maybe we punt on this for now then @bardiharborow?

**Comment by bardiharborow** [comment]
@mdo, I'd say merge this. The Function wrapper seems pointless based on everything I've read, it's more to stop Closure from being too smart and removing this entirely. The `element.offsetHeight` itself needs to be looked into by the Chrome team and should be removed eventually when the underlying bug is fixed.
