### PR TITLE
Fix modal when is triggered by `bs-toggle`, to hide other open instances

### LINKED ISSUE #34691: Toggle between modals has issue
Toggle between modals has an issue it can't close the first modal and the second modal open on it. it was worked fine on Bootstrap Version 5.0.0. But issue faced in the latest version 5.1.0.
Screenshot 2021-08-05 at 6 30 02 PM

### LINKED ISSUE #34755: Toggling between Modals does not work correctly.
Apparently this is a problem that arose as of version 5.1.0

### Steps to reproduce the problem

1. Open [https://getbootstrap.com/docs/5.1/components/modal/](https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals).
2. Go to section [Toggle between modals](https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals).
3. Click the button `Open first modal`.
4. In modal 1, click on the button `Open second modal`.
5. In modal 2, click on the button `Back to first`.
6. **The problem occurs.** Modal 2 does not close and modal one is not seen.

### Conditions in which it occurs

**Browser:** Chrome.
**OS:** Android and Windows.
**Bootstrap version:** 5.1.0

### PR DESCRIPTION
**Pull request by GeoSot**
Closes #34691 #34755

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]

File: js/src/modal.js [hunk 1]
```diff
@@ -411,6 +412,12 @@ EventHandler.on(document, EVENT_CLICK_DATA_API, SELECTOR_DATA_TOGGLE, function (
     })
   })
 
+  // avoid conflict when clicking moddal toggler while another one is open
```
Comment (tkrotoff) [inline js/src/modal.js:415]: mod**d**al => modal

avoid => Avoid ?

File: js/src/modal.js [hunk 2]
```diff
@@ -411,6 +412,12 @@ EventHandler.on(document, EVENT_CLICK_DATA_API, SELECTOR_DATA_TOGGLE, function (
...
+  const allReadyOpen = SelectorEngine.findOne(OPEN_SELECTOR)
```
Comment (tkrotoff) [inline js/src/modal.js:416]: allReady => already ?

Comment (GeoSot) [reply js/src/modal.js:416]: Both are already fix on main branch. Thank you @tkrotoff
