### PR TITLE
Multiple dropdowns: Fix when inside same tag

### LINKED ISSUE #36803: Dropdown multiple in same line collapse the same dropdown in diferent button
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When two dropdowns are used in the same row, they do not work and both are not displayed, only the first one is displayed, the same happens even in the Bootstrap 5 documentation.

In the section [Buttons with dropdowns](https://getbootstrap.com/docs/5.2/forms/input-group/)

```html
<div class="input-group">
  <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action before</a></li>
    <li><a class="dropdown-item" href="#">Another action before</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="#">Separated link</a></li>
  </ul>
  <input type="text" class="form-control" aria-label="Text input with 2 dropdown buttons">
  <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</button>
  <ul class="dropdown-menu dropdown-menu-end">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="#">Separated link</a></li>
  </ul>
</div>
```

[https://getbootstrap.com/docs/5.2/forms/input-group/](https://getbootstrap.com/docs/5.2/forms/input-group/)

### Reduced test cases

```
<div class="input-group">
  <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action before</a></li>
    <li><a class="dropdown-item" href="#">Another action before</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="#">Separated link</a></li>
  </ul>
  <input type="text" class="form-control" aria-label="Text input with 2 dropdown buttons">
  <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</button>
  <ul class="dropdown-menu dropdown-menu-end">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="#">Separated link</a></li>
  </ul>
</div>
```

[https://getbootstrap.com/docs/5.2/forms/input-group/](https://getbootstrap.com/docs/5.2/forms/input-group/)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0

### PR DESCRIPTION
**Pull request by louismaximepiton**
Proposal to fix #36803 as a quick win. I was wondering if the `data-target` was an idea for v5 or v6.

### Solution

Partial revert of #35752. For l.408 -> Use of the previous js to instantiate the dropdown with the great button.
Partial revert of #35748. For l.98 -> Use the previous `_getMenuElement()` code to have the great menu when called with the great button.

### How to check the solution

Go on the [input group section](https://deploy-preview-37011--twbs-bootstrap.netlify.app/docs/5.2/forms/input-group/#buttons-with-dropdowns).
Check that the last example (the one with 2 dropdowns) display the great dropdown menu for each dropdown toggle (`Action before` or `Action`)

### Things remaining

- [x] Do the unit tests once the solution is approved

### CODE REVIEW

File: js/src/dropdown.js [hunk 1]
```diff
@@ -405,7 +405,7 @@ class Dropdown extends BaseComponent {
 
     event.preventDefault()
 
-    const getToggleButton = SelectorEngine.findOne(SELECTOR_DATA_TOGGLE, event.delegateTarget.parentNode)
+    const getToggleButton = this.matches(SELECTOR_DATA_TOGGLE) ? this : SelectorEngine.prev(this, SELECTOR_DATA_TOGGLE)[0]
```
Comment (GeoSot) [inline js/src/dropdown.js:408]: As on Line 98 you search prev & next, I suppose we should keep the same attitude here.

In general, I would prefer to keep the right markup solution fixing the docs and adding it in migration notes, instead of doing tricks on javascipt.
I don't know if we would count that, as a breaking change but the specific example/problem, negates the suggested markup 

@cc @twbs/team

**Comment by mdo** [comment]
This PR sounds good to me if I understand it right. I get the urge for having less clever JS, but a code snippet we include in our docs no longer works after an update, so I think we should continue to support it without extra work. It's maybe less idea for us, but it keeps the developer experience better for folks building with Bootstrap :).

**Comment by GeoSot** [comment]
Ok, let's tackle it this way 

@louismaximepiton please leave a comment (// todo v6  revert #37011 & change markup https://getbootstrap.com/docs/5.2/forms/input-group/  )

**Comment by GeoSot** [comment]
@louismaximepiton please add at least a test too, to cover this case

**Comment by mdo** [comment]
Thanks both! Let me know when this is good to merge :).

**Comment by louismaximepiton** [comment]
Are you fine with the added tests cases ?

**Review by GeoSot — APPROVED** [review]

**Comment by GeoSot** [comment]
You are more than great @louismaximepiton . Thank you a lot :rocket:

File: js/tests/unit/dropdown.spec.js [hunk 2]
```diff
@@ -1458,6 +1458,67 @@ describe('Dropdown', () => {
...
+      expect(spy).toHaveBeenCalledWith(dropdownToggle2)
+
+      dropdownMenu1.click()
+      expect(spy).toHaveBeenCalledWith(dropdownToggle1)
+
+      dropdownMenu2.click()
+      expect(spy).toHaveBeenCalledWith(dropdownToggle2)
+    })
+
+    it('should be able to show the good menu, even with multiple dropdowns in the same tag', () => {
```
Comment (GeoSot) [inline js/tests/unit/dropdown.spec.js:1494]:
```suggestion
    it('should be able to show the proper menu, even with multiple dropdowns in the same tag', () => {
```
