### PR TITLE
Modal: Fix backdrop not readjusting when height changes

### LINKED ISSUE #15136: Modal Backdrop (nearly) never fits
Because of the change with modal backdrop and the new function from #15106 there are a lot of problems with the modal backdrop now.
1. It's a major break in backward compatibility. I have to rewrite the complete handling of modals to ensure that with every action inside the modal the backdrop is updated
2. Even bootstraps own functions don't use the modal handling. So with every collapsable panel inside a modal I will have problems with the backdrop.
3. Why the hell was this changed in 3.3.0? From my point of view the modals worked perfectly before 3.3.0!
4. Is there any solution to attach a "size changes" handler to the modal that updates the modal without having to manually call the the update handler?

### PR DESCRIPTION
**Pull request by hnrch02**
Fixes #15136.
Closes #15345.
Closes #15314.
Refs #14724, #14927.

Effectively reverts #14724 but still fixes #13816. The backdrop will now again be appended to the body and not the `.modal` container.
Also includes a workaround for when an opening accordion makes the modal overflow to minimize jumping on the dialog. (It's more of a proof of concept, I understand if we take it out before merging.)

/cc @cvrebert @fat @XhmikosR 

Sorry it took so long guys.

### CODE REVIEW

**Comment by cvrebert** [comment]
How does this fix #15106 exactly? `handleUpdate()` is still undocumented.

**Comment by DaSchTour** [comment]
I thought handleUpdate() wouldn't be necessary anymore?

**Comment by hnrch02** [comment]
To clarify: `handleUpdate` is no longer needed to adjust the height of the backdrop, it now only centers the modal by applying padding when the modal is overflowing. So you'd only need to call it if the height change made the modal display a scrollbar when it before didn't have one. That's not a new problem though, it's been around for much longer.

File: js/tests/unit/modal.js [hunk 1]
```diff
@@ -167,7 +167,7 @@ $(function () {
         assert.notEqual($('#modal-test').length, 0, 'modal insterted into dom')
         $('.contents').click()
         assert.ok($('#modal-test').is(':visible'), 'modal visible')
-        $('#modal-test .modal-backdrop').click()
```
Comment (cvrebert) [inline js/tests/unit/modal.js]: Forgive my confusion, but why isn't this `$('.modal-backdrop').click()`? Isn't clicking on the backdrop rather than the modal itself the whole point of this test?

Comment (hnrch02) [inline js/tests/unit/modal.js]: Well, you'll never click on the backdrop. The event listener for the `click` event is on the modal element.

File: js/modal.js [hunk 2]
```diff
@@ -14,12 +14,14 @@
...
-    this.$body          = $(document.body)
-    this.$element       = $(element)
-    this.$backdrop      =
-    this.isShown        = null
-    this.scrollbarWidth = 0
+    this.options             = options
+    this.$body               = $(document.body)
+    this.$element            = $(element)
+    this.$dialog             = this.$element.find('.modal-dialog')
+    this.$backdrop           =
```
Comment (XhmikosR) [inline js/modal.js]: I personally find this line break harder to see that it's actually an assignment. Maybe move it to the same line?

Comment (cvrebert) [inline js/modal.js]: FWIW, [other files use the same style](https://github.com/twbs/bootstrap/blob/804457c474c686d4b5f45545da0dbad5ed56e387/js/carousel.js#L20), not that I'm a fan of that style. I'd just repeat `null` if this was my code.

Comment (XhmikosR) [inline js/modal.js]: `null` is better too than that. But anyway, last time I tried bringing some sense into the JS style I hit a wall as you know :p

Comment (hnrch02) [inline js/modal.js]: I think we can change that in a future PR for all files. It's especially hard to see for people who might not quite understand who ASI works and that this is legit.

Comment (kkirsche) [inline js/modal.js]: Is there an interest in having a PR the ensures all variables use explicit assignments rather than chained ones as such?

Comment (hnrch02) [inline js/modal.js]: Sure.

Comment (XhmikosR) [inline js/modal.js]: ASI is also something I don't like either myself, but anyway, let's not get off topic.

**Comment by cvrebert** [comment]
While #15910 did add a note about needing to call `handleUpdate()`, [the API docs](https://github.com/twbs/bootstrap/blob/c80872235faaeaf1e8029665fb7674c2e1ba1d8c/docs/_includes/js/modal.html#L460) are still missing an entry for it.

**Comment by hnrch02** [comment]
True, but since `handleUpdate` can't be called with the string argument to `$.fn.modal` it would be kinda out of place there.

File: js/modal.js [hunk 3]
```diff
@@ -64,6 +66,28 @@
     this.resize()
 
     this.$element.on('click.dismiss.bs.modal', '[data-dismiss="modal"]', $.proxy(this.hide, this))
+    this.$element.on('show.bs.collapse hide.bs.collapse', function (e) {
```
Comment (fat) [inline js/modal.js]: i feel like this is making a bloated method, worse – can we move some of this logic into a handler

maybe like 

```js
this.$element.on('show.bs.collapse hide.bs.collapse', this.adjustDialogOnShowHide)
```
or some better name :+1:

File: js/modal.js [hunk 4]
```diff
@@ -64,6 +66,28 @@
...
+        that.adjustDialog()
+        if (!finished) window.requestAnimationFrame(adjustDialogPadding)
+      }
+
+      $(e.target).one('shown.bs.collapse hidden.bs.collapse', function () {
+        finished = true
+        if (!rAF) that.adjustDialog()
+      })
+
+      if (rAF) window.requestAnimationFrame(adjustDialogPadding)
```
Comment (fat) [inline js/modal.js]: do we need to adjust the dialog in the event that raf is false?

File: js/modal.js [hunk 5]
```diff
@@ -64,6 +66,28 @@
...
+      var finished = false
+      var rAF      = !!window.requestAnimationFrame
+
+      function adjustDialogPadding() {
+        that.adjustDialog()
+        if (!finished) window.requestAnimationFrame(adjustDialogPadding)
+      }
+
+      $(e.target).one('shown.bs.collapse hidden.bs.collapse', function () {
+        finished = true
```
Comment (fat) [inline js/modal.js]: what do you think about renaming `finished` to something like `transitionComplete`?

File: js/modal.js [hunk 6]
```diff
@@ -181,13 +207,18 @@
...
+        .appendTo(this.$body)
+
+      this.$element.on('click.dismiss.bs.modal', $.proxy(function (e) {
+        if (this.ignoreBackdropClick) {
+          this.ignoreBackdropClick = false
+          return
+        }
+        if (e.target !== e.currentTarget) return
+        this.options.backdrop == 'static'
+          ? this.$element[0].focus.call(this.$element[0])
```
Comment (fat) [inline js/modal.js]: out of curiosity why wasn't this just `this.$element[0].focus()` ?

File: js/modal.js (hunk 4 above)
Comment (hnrch02) [inline js/modal.js]: That is what's happening on line 80.

Comment (fat) [inline js/modal.js]: oh got it

**Comment by fat** [comment]
lgtm

**Comment by cvrebert** [comment]
> True, but since handleUpdate can't be called with the string argument to $.fn.modal it would be kinda out of place there.

@hnrch02 I think that's an oversight in and of itself. We don't intentionally make folks jump through the `.data('bs.foo')` hoop with anything else...

**Comment by hnrch02** [comment]
@cvrebert So you suggest we add `$().modal('handleUpdate')`?

**Comment by cvrebert** [comment]
Yeah.

**Comment by hnrch02** [comment]
[It is actually already accessible that way](https://github.com/twbs/bootstrap/blob/c1005f52839f56a49fea68cede63f29b35d77641/js/modal.js#L299), we just need to document it.

**Comment by DaSchTour** [comment]
So when can we expect 3.3.4?

**Comment by mdo** [comment]
Looks like the CSS changes here caused #16148. Are they necessary?

**Comment by allspain** [comment]
so is there a fix for this & #16148 being worked on?

**Comment by cvrebert** [comment]
@allspain "This" is a pull request, so it's not clear what you're referring to.

**Comment by cvrebert** [comment]
@hnrch02 Can you answer mdo's question?

**Comment by allspain** [comment]
Sorry I was referring @mdo 's question, and the bug (#16148) this pull request may have introduced. Should have been more concise.

**Comment by hnrch02** [comment]
@mdo Just wanna follow up here: I merely reverted the CSS to the pre 3.3.0/#15136 state. #16148 is a problem that exists since at least v2.
