### PR TITLE
Restore offset option for dropdown component

### LINKED ISSUE #32418: Dropdown offset option is ignored v5
With v5 the dropdown feature doesn't work with offset property.
Maybe related to #32354

It doesn't work also in the documentation:
https://getbootstrap.com/docs/5.0/components/dropdowns/#dropdown-options

The v5 version of dropdown doesn't collect the offset:
https://github.com/twbs/bootstrap/blob/1edec546cb28baf68691f0eb9e43997901359ba5/js/src/dropdown.js#L292-L308

The v4 yes:
https://github.com/twbs/bootstrap/blob/1edec546cb28baf68691f0eb9e43997901359ba5/js/src/dropdown.js#L292-L308

### PR DESCRIPTION
**Pull request by joke2k**
With Popper 2.0 the dropdown offset option was removed from bootstrap but remains in the documentation and in our :heart: s.
This is an humble PR to restore them.

Fixes #32418

### CODE REVIEW

**Comment by XhmikosR** [comment]
My problem is that I have no idea why it was removed in the first place, and if there was some special reason...

**Comment by joke2k** [comment]
> My problem is that I have no idea why it was removed in the first place, and if there was some special reason...

It think because popper changes the way to configure the offset.
I used the old tests to check. But is not fully-coverage yet

File: js/src/dropdown.js [hunk 1]
```diff
@@ -289,6 +289,31 @@ class Dropdown extends BaseComponent {
...
+      return [0, 0]
+    }
+
+    if (typeof offset === 'number') {
+      offset = [offset, 0]
+    } else if (typeof offset === 'string') {
+      offset = offset.split(',')
+      if (offset.length === 1) {
+        offset = [offset[0], 0]
+      }
```
Comment (rohit2sharma95) [inline js/src/dropdown.js:305]: IMO, now configuration should be updated as per the Popper. So it is better to accept `OffsetsFunction | [?number, ?number]`. But you can keep the string type so that offset can be passed from data attributes.

And as per your check:
```js
if (offset.length === 1) {
  offset = [offset[0], 0]
}
``` 
You are allowing and set only **Skidding** , because `[number, number]` => [[Skidding](https://popper.js.org/docs/v2/modifiers/offset/#skidding-1), [Distance](https://popper.js.org/docs/v2/modifiers/offset/#distance-1)]. It may or may not be the desired behavior. So you should mention it in the docs.

File: js/src/dropdown.js [hunk 2]
```diff
@@ -289,6 +289,31 @@ class Dropdown extends BaseComponent {
...
+
+      offset = offset.map(val => Number.parseInt(val, 10))
+    } else if (typeof offset === 'function') {
+      offset = (popper, reference, placement) => {
+        return offset({ popper, reference, placement }, this._element)
+      }
```
Comment (rohit2sharma95) [inline js/src/dropdown.js:311]: And Popper passes a single object in the offset function: https://popper.js.org/docs/v2/modifiers/offset/#options
You should use destructuring `({ placement, reference, popper })`

**Review by rohit2sharma95 — COMMENTED** [review]
Thanks for the PR :slightly_smiling_face: @joke2k
I have left a few comments, it is better to have the `offset` option in the configuration.

File: js/src/dropdown.js (hunk 1 above)
Comment (joke2k) [reply js/src/dropdown.js:305]: You're right, the configuration could be too much "smarty".
The offset option should be a shortcut.
So using javascript is better `OffsetsFunction | [?number, ?number]` as you said, 
with data attribute is better to use the `"Number,Number"` format.
If anybody needs more can use popperConfig :D

File: js/src/dropdown.js (hunk 2 above)
Comment (joke2k) [reply js/src/dropdown.js:311]: To be honest, my intention was to pass one object as the first parameter (like was for offsets in bs4)
so it is my mistake on reading Popper docs.

**Comment by rohit2sharma95** [comment]
@joke2k Can you make the update, please?

File: js/src/dropdown.js [hunk 3]
```diff
@@ -72,7 +72,7 @@ const PLACEMENT_RIGHT = isRTL ? 'left-start' : 'right-start'
 const PLACEMENT_LEFT = isRTL ? 'right-start' : 'left-start'
 
 const Default = {
-  offset: 0,
+  offset: [0, 0],
```
Comment (joke2k) [inline js/src/dropdown.js:75]: New default

File: js/src/dropdown.js [hunk 4]
```diff
@@ -81,7 +81,7 @@ const Default = {
 }
 
 const DefaultType = {
-  offset: '(number|string|function)',
+  offset: '(array|string|function)',
```
Comment (joke2k) [inline js/src/dropdown.js:84]: New DefaultType

File: js/src/dropdown.js [hunk 5]
```diff
@@ -289,6 +289,24 @@ class Dropdown extends BaseComponent {
...
+
+    if (!offset) {
+      return [0, 0]
+    }
+
+    if (typeof offset === 'string') {
+      offset = offset.split(',').map(val => Number.parseInt(val, 10))
+    } else if (typeof offset === 'function') {
+      offset = ({ popper, reference, placement }) => {
+        return offset({ popper, reference, placement }, this._element)
```
Comment (rohit2sharma95) [inline js/src/dropdown.js:303]: Destructuring here might be ignored because destructuring is not being used in real, thanks for considering previous comment :grin:

---
Popper may call the `offset` function multiple times, and because the `offset` function is in the closure I am getting the error: **Maximum call stack size exceeded** (You can check by creating dist files locally and passing a function to the offset in dropdowns configuration)

My suggestion:
```js
if (typeof offset === 'string') {
  return offset.split(',').map(val => Number.parseInt(val, 10))
}

if (typeof offset === 'function') {
  return popperData => {
    return offset(popperData, this._element)
  }
}
```

File: js/tests/unit/dropdown.spec.js [hunk 6]
```diff
@@ -54,6 +54,42 @@ describe('Dropdown', () => {
...
+      fixtureEl.innerHTML = [
+        '<div class="dropdown">',
+        '  <button class="btn dropdown-toggle" data-bs-toggle="dropdown">Dropdown</button>',
+        '  <div class="dropdown-menu">',
+        '    <a class="dropdown-item" href="#">Secondary link</a>',
+        '  </div>',
+        '</div>'
+      ].join('')
+
+      const getOffset = () => [10, 20]
```
Comment (rohit2sharma95) [inline js/tests/unit/dropdown.spec.js:67]: It is better if you create a spy and  then expect that to have been called after showing the dropdown :slightly_smiling_face:

Comment (joke2k) [reply js/tests/unit/dropdown.spec.js:67]: yeah, I tried but I'm not confident with javascript mocking yet.
I'm working on it

File: js/src/dropdown.js (hunk 5 above)
Comment (joke2k) [reply js/src/dropdown.js:303]: I found this "strange" behaviour in js:
```
let x = () => 1
x() // print 1
x = () => x()
x() // infinite recursion
```
so I've to rewrite the variable name in this script.

File: js/tests/unit/dropdown.spec.js (hunk 6 above)
Comment (joke2k) [reply js/tests/unit/dropdown.spec.js:67]: The funny thing is that the `shown.bs.dropdown` is not related to Popper, so in order to test that a getOffset spy function has been called showing the dropdown I've to use the `popperConfig.onFirstUpdate` attribute.

File: site/content/docs/5.0/components/dropdowns.md [hunk 7]
```diff
@@ -896,6 +896,16 @@ Options can be passed via data attributes or JavaScript. For data attributes, ap
       <td><code>'dynamic'</code></td>
       <td>By default, we use Popper for dynamic positioning. Disable this with <code>static</code>.</td>
     </tr>
+    <tr>
+      <td><code>offset</code></td>
+      <td>number | string | function</td>
+      <td><code>"0,0"</code></td>
```
Comment (rohit2sharma95) [inline site/content/docs/5.0/components/dropdowns.md:902]: Default value for offset is array @joke2k :slightly_smiling_face: 
```js
offset: [0, 0],
```

Comment (joke2k) [reply site/content/docs/5.0/components/dropdowns.md]: I changed a little bit the copy

**Comment by rohit2sharma95** [comment]
It is now complete for dropdown though but the same should be done for Tooltip/Popover also, IMO.
Ping @XhmikosR :slightly_smiling_face:

**Review by rohit2sharma95 — APPROVED** [review]

**Comment by javieraviles** [comment]
If I'm not wrong, scrollspy offset is under the same use-case. In alpha v5 is not working either.

**Comment by joke2k** [comment]
> If I'm not wrong, scrollspy offset is under the same use-case. In alpha v5 is not working either.

I checked into bs4 and bs5 but ScrollSpy component never used Popper for its offset.
In beta1 Scrollspy offset option works pretty well

https://jsfiddle.net/yhv62bz1/

File: js/src/dropdown.js [hunk 8]
```diff
@@ -289,6 +289,20 @@ class Dropdown extends BaseComponent {
     return this._element.closest(`.${CLASS_NAME_NAVBAR}`) !== null
   }
 
+  _getOffset() {
```
Comment (XhmikosR) [inline js/src/dropdown.js:292]: @rohit2sharma95 this seems to be duplicated. Might be worth checking at a later time if we it makes sense to deduplicate this. Lower priority right now :)

Comment (rohit2sharma95) [reply js/src/dropdown.js:292]: Yes, should tackle it in a new PR later?

**Comment by javieraviles** [comment]
> > If I'm not wrong, scrollspy offset is under the same use-case. In alpha v5 is not working either.
> 
> I checked into bs4 and bs5 but ScrollSpy component never used Popper for its offset.
> In beta1 Scrollspy offset option works pretty well
> 
> https://jsfiddle.net/yhv62bz1/

I thought the offset would not only be applied when scrolling manually to detect which button should be highlighted but also when clicking on the button to have such offset applied in the scroll. My bad

File: js/src/dropdown.js (hunk 8 above)
Comment (joke2k) [reply js/src/dropdown.js:292]: I'm trying to deduplicate this into `utils/index.js` and I was wondering if we can do the same for `_getPopperConfig`...
but the function signature becoming a little bit weird:
```js
const getPopperOffsets = (element, config) => {
  if (typeof offset === 'string') {
    return offset.split(',').map(val => Number.parseInt(val, 10))
  }

  if (typeof offset === 'function') {
    return popperData => offset(popperData, element)
  }

  return offset
}

const getPopperConfig = (element, placement, offset, modifiers, options) => {
  const defaultBsConfig = {
    placement: placement,
    modifiers: [...(modifiers || [])],
    ...(options || {})
  }

  if (offset) {
    defaultBsConfig.modifiers.push({
      name: 'offset',
      options: {
        offset: getPopperOffsets(element, offset)
      }
    })
  }

  return defaultBsConfig
}
```
the `element` is necessary because offset configured as function needs it for the second parameter.

Comment (XhmikosR) [reply js/src/dropdown.js:292]: No need to do this now. We'll have plenty of time after this lands :)

**Comment by rohit2sharma95** [comment]
I also notice if someone wants to pass the `offset` option (Or any other modifier for Popper) via the `popperConfig` option, **the other modifiers are replaced by the array of the modifiers passed in the popperConfig.**

So if the user passes only one modifier in the array of `popperConfig`, other modifiers are reset to the defaults used by Popper.
https://github.com/twbs/bootstrap/blob/86802f701cdff9a2fe91278fe42684a32426bc61/js/src/dropdown.js#L318-L322

So few options should be maintained individually by Bootstrap that are customized by bootstrap. For example, the default value for `fallbackPlacements` is changed by Bootstrap. And the `offset` option is one of them.

And it should be mentioned in the docs that if someone passes the configuration via `popperConfig`, it is kind of handling the Popper's configuration natively because it can override some of the default configurations by bootstrap.

/CC @XhmikosR @MartijnCuppens

**Comment by mdo** [comment]
@rohit2sharma95 @XhmikosR Should we open an issue or PR to track that separately so we can merge this?

**Comment by rohit2sharma95** [comment]
Yes, either the docs should be updated or the way of merging the popperConfig in the plugins.
