### PR TITLE
fix live toast demo

### LINKED ISSUE #33906: Toast-timing is very inconsistent.
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) **Done, couldn't find any.**
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems. **Done, just two warnings because I generate some stuff with JS.**
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md) **Done.**

## Toast-timing is very inconsistent.
Sometimes it's the regular delay (for example 10 seconds), but sometimes the toast just disappears way quicker.

- Operating system and version: Linux Mint 20.1 Cinnamon
- Browser and version: Firefox
- I'm not sure how to compile that code into a test-case but I took a screen capture:

https://user-images.githubusercontent.com/59611881/117564418-3c738800-b0ac-11eb-8cc8-f9ed8f1fb249.mp4

### PR DESCRIPTION
**Pull request by AucT**
### Description

Fixed your example

### Motivation & Context

Change is required for toast work without glitches.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

* https://deploy-preview-37590--twbs-bootstrap.netlify.app/docs/5.3/components/toasts/
* https://codepen.io/AucT/pen/KKebEMW

### Related issues

Fixes #33906

### CODE REVIEW

**Comment by AucT** [comment]
I'm very noob to this github merging and forking stuff.
So if something is wrong - cancel pull and make as it should be.

**Comment by julien-deramond** [comment]
Yep don't worry. We'll take a look at your PR asap. Thanks for opening it btw.

**Review by mdo — APPROVED** [review]
Confirmed in the demos that this is better, thanks!

**Comment by XhmikosR** [comment]
This needs a rebase, and I'd like to hear @GeoSot's opinion too.

File: site/assets/js/snippets.js [hunk 1]
```diff
@@ -63,11 +63,11 @@
   // Instantiate all toasts in a docs page only
   const toastTrigger = document.getElementById('liveToastBtn')
   const toastLiveExample = document.getElementById('liveToast')
+  const toastBootstrap = new bootstrap.Toast(toastLiveExample)
```
Comment (XhmikosR) [inline site/assets/js/snippets.js:66]: Shouldn't we instantiate this only if there's a `toastTrigger`? Doesn't make a lot of sense to do otherwise...

File: site/assets/js/snippets.js [hunk 2]
```diff
@@ -60,14 +60,14 @@
...
 
-  // Instantiate all toasts in a docs page only
+  // Instantiate all toasts in docs pages only
   const toastTrigger = document.getElementById('liveToastBtn')
   const toastLiveExample = document.getElementById('liveToast')
+  const toastBootstrap = new bootstrap.Toast(toastLiveExample)
+
   if (toastTrigger) {
     toastTrigger.addEventListener('click', () => {
-      const toast = new bootstrap.Toast(toastLiveExample)
```
Comment (GeoSot) [inline site/assets/js/snippets.js:68]: I don't think it would make any difference, if we just change this to 
`bootstrap.Toast.getOrCreateInstace`, ensuring we handle it after clicking

File: site/content/docs/5.3/components/toasts.md [hunk 3]
```diff
@@ -90,11 +90,11 @@ We use the following JavaScript to trigger our live toast demo:
 ```js
 const toastTrigger = document.getElementById('liveToastBtn')
 const toastLiveExample = document.getElementById('liveToast')
+const toastBootstrap = new bootstrap.Toast(toastLiveExample)
+
 if (toastTrigger) {
   toastTrigger.addEventListener('click', () => {
-    const toast = new bootstrap.Toast(toastLiveExample)
```
Comment (GeoSot) [inline site/content/docs/5.3/components/toasts.md:95]: same as above
