### PR TITLE
Selector Engine: fix multiple IDs

### LINKED ISSUE #39189: invalid selector regression in 5.3.2
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

After updating to Bootstrap 5.3.2 we have errors where modals are failing to open due to the query selector failing as invalid 

```
selector-engine.js:41 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#j_id22:exampleModal' is not a valid selector.
    at Object.findOne (https://cdn.jsdelivr.net/npm/bootstrap@latest/dist/js/bootstrap.bundle.min.js:6:8558)
    at Object.getElementFromSelector (https://cdn.jsdelivr.net/npm/bootstrap@latest/dist/js/bootstrap.bundle.min.js:6:9299)
    at HTMLButtonElement.<anonymous> (https://cdn.jsdelivr.net/npm/bootstrap@latest/dist/js/bootstrap.bundle.min.js:6:55221)
    at HTMLDocument.n (https://cdn.jsdelivr.net/npm/bootstrap@latest/dist/js/bootstrap.bundle.min.js:6:4238)
```

The target is like `data-bs-target="#j_id22:exampleModal"`. This is a common auto generated identifier from JSF where `:` is used as a seperator.

This code works in 5.3.1 but fails in 5.3.2

### Reduced test cases

Working in 5.3.1: https://codepen.io/codylerum/details/OJrjvBx

Failing in 5.3.2: https://codepen.io/codylerum/pen/WNLEzKz

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.2

### PR DESCRIPTION
**Pull request by GeoSot**
### Motivation & Context

A draft solution, which supports multiple ids, and usage off CSS.escape at the same time

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-39201--twbs-bootstrap.netlify.app/>

### Related issues

Ref: #38989 , #339198

closes: #39189

### CODE REVIEW

**Review by julien-deramond — COMMENTED** [review]
I haven't checked everything in detail but I was thinking about the same kind of patch when I tried to analyse the issue.
Your patch fixes the issue, and the multiple target ids system is still working.

Ideas of improvement:
* Add a new test with a multiple target ids containing special chars; something like the following:

```js
    it('should get elements if several ids with special chars are given', () => {
      fixtureEl.innerHTML = [
        '<div id="test" data-bs-target="#j_id11:exampleModal,#j_id22:exampleModal"></div>',
        '<div class="target" id="j_id11:exampleModal"></div>',
        '<div class="target" id="j_id22:exampleModal"></div>'
      ].join('')

      const testEl = fixtureEl.querySelector('#test')

      expect(SelectorEngine.getMultipleElementsFromSelector(testEl)).toEqual(Array.from(fixtureEl.querySelectorAll('.target')))
    })
```

* Add other tests with _weird_ authorized characters as IDs to check that the selector engine escapes the special chars when needed. If I understand well the HTML 5 spec, it seems that almost all characters are authorized except spaces in IDs.
  * Note: not for this PR but maybe in the future we should change the separator for `data-bs-target` (with multiple targets) to replace `,` which seems to be authorized as a character in IDs.

FWIW, it doesn't seem that https://github.com/twbs/bootstrap/issues/39198 is linked to this regression and is rather linked to some bad usage + a possible missing escape of characters in scrollspy's JS with anchors. So another topic.

**Review by julien-deramond — APPROVED** [review]
LGTM as explained in https://github.com/twbs/bootstrap/pull/39201#pullrequestreview-1631418743.

I've added an unit test for `SelectorEngine` too via https://github.com/twbs/bootstrap/pull/39201/commits/e9c649ba140f30100c9fc65bf106a354c46d01ac. Feel free to revert this commit if you don't agree with this approach.

@XhmikosR and/or @GeoSot, I let you double-check this fix in depth and determine if we need to release it in v5.3.3 soon.

File: js/src/dom/selector-engine.js [hunk 1]
```diff
@@ -26,10 +26,10 @@ const getSelector = element => {
       hrefAttribute = `#${hrefAttribute.split('#')[1]}`
     }
 
-    selector = hrefAttribute && hrefAttribute !== '#' ? parseSelector(hrefAttribute.trim()) : null
+    selector = hrefAttribute && hrefAttribute !== '#' ? hrefAttribute.trim() : null
   }
 
-  return selector
+  return selector?.split(',').map(sel => parseSelector(sel)).join(',')
```
Comment (XhmikosR) [inline js/src/dom/selector-engine.js:32]: I wouldn't use optional chaining yet since IIRC we don't use it anywhere yet. We could switch at some point, not sure when, though :)
