### PR TITLE
Fix modal event listeners

### LINKED ISSUE #37126: Since 5.2.1 modals closes on content removal
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Since version 5.2.1, when a button in the modal body triggers the removal of the button itself or its parent, the modal closes. It worked correctly with version 5.2.0.

**Edit:**

Definitely related to #36863, reverting it fixes the issue.

### Reduced test cases

For both test cases, click on the "Open modal" button then click on any "Remove row" button.

- With Bootstrap 5.2.0: https://codepen.io/jbroutier/pen/JjvKzqZ
- With Bootstrap 5.2.1: https://codepen.io/jbroutier/pen/dyeXrLQ

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.2.1

### PR DESCRIPTION
**Pull request by ghost**
Add a check to ensure that the element that triggered the event is still present in the DOM.

closes https://github.com/twbs/bootstrap/issues/37126

Supersedes  #37143

### CODE REVIEW

**Comment by GeoSot** [comment]
@jbroutier Thank you for your PR.
Can you please a test-case to justify the change?

**Comment by GeoSot** [comment]
I've linted a bit, but got another idea too. 
You may, instead of two `contain` checks, to try this
```js
        if (this._element !== event.target || this._element !== event2.target) {
          return
        }
```

it should work too and it covers both cases

File: js/src/modal.js [hunk 1]
```diff
@@ -224,8 +224,8 @@ class Modal extends BaseComponent {
 
     EventHandler.on(this._element, EVENT_MOUSEDOWN_DISMISS, event => {
       EventHandler.one(this._element, EVENT_CLICK_DISMISS, event2 => {
-        // a bad trick to segregate clicks that may start inside dialog but end outside, and avoid listen to scrollbar clicks
-        if (this._dialog.contains(event.target) || this._dialog.contains(event2.target)) {
+        // handle click on removed elements
```
Comment (GeoSot) [inline js/src/modal.js]:
```suggestion

```

**Review by GeoSot — APPROVED** [review]
