### PR TITLE
Reset inside a Dialog does not work if `data-dismiss="modal"` is set

### LINKED ISSUE #33469: Reset inside a Dialog does not work if data-dismiss="modal" is set.
Hello, I found an issue when using the reset form button inside a Dialog.
If the button does reset and dismissal by using data-dismiss="modal", the dialogs close fine but the form is never reset.

Test case on codepen: https://codepen.io/meduzapat/pen/LYxpGNe

I added 3 buttons, normal close, reset and close, and my work around: reset and js close.

Tested on:
Chrome OS, Linux: Firefox 86.0.1 (64-bit) and chrome Version 89.0.4389.90 (Official Build) (64-bit) an Windows.

### PR DESCRIPTION
**Pull request by GeoSot**
closes #33469

[example on codepen](https://codepen.io/GeosSV/pen/dyvYpNx)

### CODE REVIEW

File: js/src/modal.js [hunk 1]
```diff
@@ -271,8 +271,8 @@ class Modal extends BaseComponent {
     EventHandler.off(document, EVENT_FOCUSIN) // guard against infinite focus loop
     EventHandler.on(document, EVENT_FOCUSIN, event => {
       if (document !== event.target &&
-          this._element !== event.target &&
-          !this._element.contains(event.target)) {
+        this._element !== event.target &&
+        !this._element.contains(event.target)) {
```
Comment (rohit2sharma95) [inline js/src/modal.js:275]: Unrelated change :slightly_smiling_face:

File: js/tests/unit/modal.spec.js [hunk 2]
```diff
@@ -988,6 +988,60 @@ describe('Modal', () => {
       trigger.click()
     })
 
+    it('should not prevent default default when a click occurred on data-bs-dismiss="modal" where tagName is DIFFERENT than <a> or <area>', done => {
```
Comment (rohit2sharma95) [inline js/tests/unit/modal.spec.js:991]: **default** x2

File: js/tests/unit/modal.spec.js [hunk 3]
```diff
@@ -988,6 +988,60 @@ describe('Modal', () => {
...
+
+      modalEl.addEventListener('hidden.bs.modal', () => {
+        expect(Event.prototype.preventDefault).not.toHaveBeenCalled()
+        done()
+      })
+
+      modal.show()
+    })
+
+    it('should prevent default default when a click occurred on data-bs-dismiss="modal" where tagName is <a> or <area>', done => {
```
Comment (rohit2sharma95) [inline js/tests/unit/modal.spec.js:1018]: Here as well (default)

**Review by rohit2sharma95 — APPROVED** [review]
